### ISSUE TITLE
geom_ribbon_pattern

### ISSUE THREAD

**Issue by gilleschapron** [coolbutuseless/ggpattern#13]
Hello Mike,

I look forward to add pattern to some geological cross section I made with ggplot2.
When you have some time, could you add a ribbon geometry ?

Thanks !

**Comment by coolbutuseless** [comment]
There is already a geom_ribbon_pattern. Please let me know if it is not working for you.

**Comment by gilleschapron** [comment]
I'm sorry, as I did not find it in the reference I didn't even get the idea to test it! It works perfectly.
That's awesome.
Hope this very useful package will be soon on CRAN.
Thanks
