### ISSUE TITLE
FR: Add lacking geoms

### ISSUE THREAD

**Issue by iago-pssjd** [coolbutuseless/ggpattern#14]
I was looking for filling a plot with patterns and I found this great package. Unfortunately, I need fill the patterns on `geom_linerange` and `ggstance::geom_linerangeh` not covered by it. But I believe that when this package cover all the geoms, at least from `ggplot`, it will be very relevant.

Thank you!

**Comment by coolbutuseless** [comment]
Could you provide an image or example code of what you want to fill with a pattern?

As I understand it, a 'linerange' is a line object, and thus doesn't really have an area to fill.

**Comment by iago-pssjd** [comment]
Yes, you are right, I was thinking in `linerange` with enough size so it has width.
```r
df <- data.frame(
    trt = factor(c(1, 1, 2, 2)),
    resp = c(1, 5, 3, 4),
    group = factor(c(1, 2, 1, 2)),
    upper = c(1.1, 5.3, 3.3, 4.2),
    lower = c(0.8, 4.6, 2.4, 3.6)
)

p <- ggplot(df, aes(trt, resp, colour = group))
p + geom_linerange(aes(ymin = lower, ymax = upper), size = 4)
```

![image](https://user-images.githubusercontent.com/40892925/102665257-cdd97080-4184-11eb-92c0-78856508bb56.png)

**Comment by coolbutuseless** [comment]
Ah I see what you want, but this is not possible with ggpattern.

ggpattern will fill *areas*, but thick lines are not geometrically an area, and there is no current way to fill them.
