### ISSUE TITLE
I can't install the package... "units" error

### ISSUE THREAD

**Issue by RuiPChaves** [coolbutuseless/ggpattern#16]
I can't install the package because (Error: Failed to install 'ggpattern' from GitHub) because of some other package called units.
See below. All and any help much appreciated.

`ERROR: configuration failed for package ‘units’
* removing ‘/home/rpc/R/x86_64-pc-linux-gnu-library/3.6/units’
Error: Failed to install 'ggpattern' from GitHub:
  (converted from warning) installation of package ‘units’ had non-zero exit status`

... later I solved that with:
sudo apt install libudunits2-dev
but then had problems installing magick, which I solved with 
sudo apt-get install libmagick++-dev
and then had problems with 'sf', and down the rabbit hole we go..

**Comment by coolbutuseless** [comment]
Hi @RuiPChaves  - 

Thanks for the feedback.  I can't really do anything about other packages which have trouble installing.

For now I'm going to add a few more standard pre-requisites to the installation instructions and hopefully this will alleviate some errors.

Please let me know if you managed to install.
