### ISSUE TITLE
Failed to install 'ggpattern' from GitHub

### ISSUE THREAD

**Issue by kevin-dp** [coolbutuseless/ggpattern#18]
I'm trying to install the package as explained in the readme, however, i always get the error:
Error: Failed to install 'ggpattern' from GitHub:
  (converted from warning) installation of package '/var/folders/64/vfwg9p_d4cd9yggl26s12s580000gn/T//Rtmpem8JAo/file12a3e49ad4219/ggpattern_0.1.3.tar.gz' had non-zero exit status

I tried installing ggpattern in R 4.0.3 and also in a clean install of R version 3.6.3 but i get the same error.

Here is the complete log:

```
> remotes::install_github("coolbutuseless/ggpattern")
Downloading GitHub repo coolbutuseless/ggpattern@HEAD
tar: Failed to set default locale
tar: Failed to set default locale
   checking DESCRIPTION meta-information ...4/vfwg9p_d4cd9yggl26s12s580000gn/T/Rtmpem8JAo/remotes12a3e8aa791d/coolbutuseless-ggpattern-8c5abf9/DESCRIPTION' ...
Error: (converted from warning) Setting LC_CTYPE failed, using "C"
Execution halted
Error: Failed to install 'ggpattern' from GitHub:
  (converted from warning) installation of package '/var/folders/64/vfwg9p_d4cd9yggl26s12s580000gn/T//Rtmpem8JAo/file12a3e6ff5635c/ggpattern_0.1.3.tar.gz' had non-zero exit status
```

**Comment by M-Colley** [comment]
seconded, using R 4.0.3 I can't install ggpattern, unfortunately

**Comment by danielaags** [comment]
same here, I can't install ggpattern, I am also using R 4.0.3

**Comment by coolbutuseless** [comment]
Could you all try a few things:

* update to latest {remotes}
* update to latest {devtools}

If you still have no luck, please respond with some more details on your Operating System

**Comment by M-Colley** [comment]
Check updates showed no updates but via install packages I updated the packages, via 

`remotes::install_github("coolbutuseless/ggpattern", force = TRUE)`

it actually worked!

thanks!

**Comment by coolbutuseless** [comment]
@kevin-dp , @M-Colley could you try again?

**Comment by coolbutuseless** [comment]
I've edited in some more explicit instructions on installing dependencies first.

If anyone is still having problems, please open a fresh github issue. Thanks.

**Comment by LucyNjoki** [comment]
> Check updates showed no updates but via install packages I updated the packages, via
> 
> `remotes::install_github("coolbutuseless/ggpattern", force = TRUE)`
> 
> it actually worked!
> 
> thanks!

Thank you so much for this.:) I have been struggling to install it for the last hour!!
