### ISSUE TITLE
error when running example script: Error in if (type == "point") { : argument is of length zero

### ISSUE THREAD

**Issue by robbiestill** [coolbutuseless/ggpattern#2]
Hi Mike, 

I've installed the package from github, and I'm getting an error when trying to run the example code to make an sf plot with patterns (see below):

The error message is this: `Error in if (type == "point") { : argument is of length zero `

```
library(ggpattern)
nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE) 
nc <- nc %>% filter(between(CNTY_ID, 1820, 1830))

p <- ggplot(nc) +
  geom_sf_pattern(
    aes(
      pattern = NAME,
      fill    = NAME
    ),
    pattern_aspect_ratio = 2.8
  ) +
  theme_bw(15) +
  theme(legend.key.size = unit(1.5, 'cm')) +
  labs(title = "ggpattern::geom_sf()")

p

```

**Comment by coolbutuseless** [comment]
Could you include your version of R, ggplot2 and sf?

Your code runs fine for me. on MaxOS, R3.6.1, ggplot2 3.3.0.9000, sf 0.8.1

That error occurs in a bit of code cloned from `geom_sf`.  

Could you trying changing the geom from `geom_sf_pattern()` to `geom_sf()` and see if the error still occurs?

**Comment by robbiestill** [comment]
I've updated ggplot and its now working, the error originally occurred when substituting `geom_sf()` to `geom_sf_pattern()` in a previous script so it did work when the code was just `geom_sf()`, but updating ggplot2 seems to have fixed it.
