### ISSUE TITLE
Error in sprintf("―") : invalid multibyte string at '<95>'

### ISSUE THREAD

**Issue by chengroup** [coolbutuseless/ggpattern#22]
I used the example data and found an error about "spingtf()". Any method?

> data <- read.csv(system.file("extdata", "monthlyexp.csv", package="patternplot"))
> group<-factor(data$Type, c('Housing', 'Food',  'Childcare'))
> y<-data$Amount
> x<-factor(data$Location, c('City 1', ' City 1'))
> pattern.type<-c( 'Rsymbol_16', 'blank','hdashes')
> pattern.color=c('yellow', 'chartreuse4',  'pink')
> background.color=c('grey', 'chartreuse3',  'bisque')
> patternbar(data,x, y,group,ylab='Monthly Expenses, Dollars', pattern.type=pattern.type)
Error in sprintf("―") : invalid multibyte string at '<95>'

**Comment by coolbutuseless** [comment]
Hi @chengroup ,

In order for me to debug this I need a reproducible example which I can run on my setup.

See this link for some information on reproducible examples: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example

**Comment by trevorld** [comment]
A minimal, reproducible example was never provided.
