### ISSUE TITLE
Pattern going over edges

### ISSUE THREAD

**Issue by johnhenrypezzuto** [coolbutuseless/ggpattern#24]
Do you have any advice for keeping patterns from going off the edge? This isn't an extreme case but it is fairly noticeable

``` r
library(ggpattern)
library(ggplot2)
library(dplyr)

mtcars %>% 
  mutate(cyl = factor(cyl)) %>% 
  ggplot(aes(cyl)) +
  geom_bar_pattern(pattern = "circle", 
                   pattern_fill = 'black', 
                   pattern_density = .5,
                   width = .8)
```

![](https://i.imgur.com/0xJZmcR.png)

<sup>Created on 2021-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

ggpattern_0.1.3

**Comment by johnhenrypezzuto** [comment]
One temp hack I've figured out is to just fill the color as the same color as the bar.
``` r
library(ggpattern)
library(ggplot2)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
mtcars %>% 
  mutate(cyl = factor(cyl)) %>% 
  ggplot(aes(cyl, col = "fake border")) +
  geom_bar_pattern(pattern = "circle", 
                   pattern_fill = 'black', 
                   pattern_density = .5,
                   col = "#595959",
                   width = .8)
```

![](https://i.imgur.com/2YcszNz.png)

<sup>Created on 2021-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


Although this won't work if the bars are filled with multiple colors.

**Comment by johnhenrypezzuto** [comment]
e.g.,

``` r
library(ggpattern)
library(ggplot2)
library(dplyr)


diamonds %>% 
  ggplot(aes(cut, fill = color, col = color)) +
  geom_bar_pattern(pattern = "circle", 
                   pattern_fill = 'black', 
                   pattern_density = .5,
                   width = .8)
```

![](https://i.imgur.com/aQoij8L.png)

<sup>Created on 2021-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by johnhenrypezzuto** [comment]
But I suppose if you're feeling really hack you can double down on `geom_bar_pattern` to fix that too.
``` r
library(ggpattern)
library(ggplot2)
library(dplyr)

diamonds %>% 
  ggplot(aes(cut, fill = color, col = color)) +
  geom_bar_pattern(pattern = "circle",
                   pattern_fill = 'black',
                   pattern_density = .5,
                   width = .8) +
  geom_bar_pattern(aes(col = NULL),
                   pattern = "circle", 
                   pattern_fill = 'black', 
                   pattern_density = .5,
                   width = .8)
```

![](https://i.imgur.com/jocK5NC.png)

<sup>Created on 2021-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by trevorld** [comment]
The simpler alternative would be to **remove** the boundary line from **both** the pattern circles and bars by making them transparent (or alternatively setting their size to zero):

```r
library(ggpattern)
library(ggplot2)
library(dplyr)

diamonds %>%
  ggplot(aes(cut, fill = color)) +
  geom_bar_pattern(pattern = "circle",
                   pattern_fill = 'black',
                   colour = NA,
                   pattern_colour = NA,
                   pattern_alpha = NA,
                   pattern_density = .5,
                   width = .8)
```

![Rplot001](https://user-images.githubusercontent.com/2433259/124332004-47471800-db45-11eb-8b66-a1afd564127c.png)
