### ISSUE TITLE
Fall to install package

### ISSUE THREAD

**Issue by tiaozaoxia** [coolbutuseless/ggpattern#25]
Hi Sir,
I have trouble in installing the package. The error is
"downloading GitHub repo coolbutuseless/ggpattern@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet, :
download from 'https://api.github.com/repos/coolbutuseless/ggpattern/tarball/HEAD' failed".

My R version is 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out".
I want to know how to solve this problem.
Thank you,
Cheers.

**Comment by trevorld** [comment]
* Sorry you were unable to install {ggpattern}.
* See https://thomasadventure.blog/posts/install-r-packages/ for more info on installing packages.
* This seems to be some kind of personal network issue unrelated to {ggpattern} development.  You may want to try again?
