### ISSUE TITLE
Support polygons with holes

### ISSUE THREAD

**Issue by eliocamp** [coolbutuseless/ggpattern#26]
I want to use ggpatern to hatch areas of a field with values greater (or lower) than some reference value using contours. However, this doesn't work well because of the lack of support for polygons with holes. 

This would be a killer feature for me. Will it be implemented in the near future? If you know where in the code it should be implemented, Id' be happy to give it a try.

**Comment by eliocamp** [comment]
Chainging this line 

https://github.com/coolbutuseless/ggpattern/blob/390e13fead028ba240eae9293a5ef422df02bc8e/R/geom-polygon.R#L121

to 

```r
first_idx <- !duplicated(interaction(munched$group, munched$subgroup))
```

and this
 https://github.com/coolbutuseless/ggpattern/blob/390e13fead028ba240eae9293a5ef422df02bc8e/R/geom-polygon.R#L128

to 

```r
polygons <- split(munched, interaction(munched$group, munched$subgroup))
```


Seems to work a lot better in my example case. 
![image](https://user-images.githubusercontent.com/8617595/108525826-45c03600-72af-11eb-9b25-d119f5dcab43.png)


To this:

![image](https://user-images.githubusercontent.com/8617595/108525907-5375bb80-72af-11eb-8322-549892262b25.png)

**Comment by trevorld** [comment]
* Do you have a minimal, reproducible example of a `geom_polygon()` (not `geom_pattern_polygon()`) call with holes? #44 
* Recent {ggpattern} / {grid} changes mean the "no hole" restriction might be liftable for certain geoms

**Comment by trevorld** [comment]
Minimal reproducible example with holes:
```
      # example modified from {ggplot2} unit tests
      tbl <- data.frame(
        x = c(
          0, 10, 10, 0,
          20, 30, 30, 20,
          22, 28, 28, 22
        ),
        y = c(
          0, 0, 10, 10,
          20, 20, 30, 30,
          22, 22, 28, 28
        ),
        group = c(rep(1, 4), rep(2, 8)),
        subgroup = c(rep(1, 8), rep(2, 4))
      )

      p <- ggplot(tbl, aes(x, y, group = group, subgroup = subgroup)) +
        geom_polygon_pattern(fill="lightblue", color="black")
```
