### ISSUE TITLE
Reverse stripe angles

### ISSUE THREAD

**Issue by caston60** [coolbutuseless/ggpattern#29]
A much needed addition to the ggplot world, thank you.

Having an issue with controlling the angle and I cannot seem to find a solution on the web.  I can set an angle to 45 and have nice stripes from lower left to upper right, but I also need bars with the reverse stripe: from upper left to lower right.  I have tried setting pattern_angle = -45, 135 and 315 but to no avail (I just get vertical stripes).  What am I missing here?

-chris

**Comment by trevorld** [comment]
No minimal reproducible-example provided.
