### ISSUE TITLE
"There is no package called EBImage" Error

### ISSUE THREAD

**Issue by VictimOfMaths** [coolbutuseless/ggpattern#3]
When I try and use the placeholder fills following the approach in the vignette I get this error message.

![Capture](https://user-images.githubusercontent.com/48697887/80024435-fcf4f080-84d6-11ea-89a6-3e85592a596c.PNG)

I have no problem at all with the regular pattern fills though

![image](https://user-images.githubusercontent.com/48697887/80024642-4d6c4e00-84d7-11ea-9f5f-fc47ff92c29b.png)

![image](https://user-images.githubusercontent.com/48697887/80024606-3fb6c880-84d7-11ea-955d-16302aad3201.png)

**Comment by coolbutuseless** [comment]
EBImage is a package from Bioconductor used by `magick`

I have filed an issue upstream to see if it can be addressed there: https://github.com/ropensci/magick/issues/241

In the meantime I will add the dependency to `ggpattern`.

The workaround for now is to:

```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("EBImage")
```


See here for further info on the EBImage package: https://www.bioconductor.org/packages/release/bioc/html/EBImage.html

**Comment by coolbutuseless** [comment]
I think I need to remove my reliance on `as_EBImage` and switch to `magick::image_data()` instead.   Not sure of the differences.
