### ISSUE TITLE
Use svgpatternusgs into ggpattern

### ISSUE THREAD

**Issue by gilleschapron** [coolbutuseless/ggpattern#31]
Hi,

Thank you for your fantastic work on this package.
Do you have plan to connect your package svgpatternusgs to ggpattern ? could be a fantastic tool for a geologist like me.
Or is it maybe already possible ?

Regards,

Gilles

**Comment by trevorld** [comment]
You could write a "custom" pattern and use it.  One possible approach could use in "custom" pattern:

* Save 'svg' image using `{svgpatternusgs}` and `{minisvg}`
* Convert to png (perhaps `{magick}` can read the svg image and this is optional)?
* Use the `{gridpattern}` "image" pattern with that image
