### ISSUE TITLE
How to add hatches on spatail dataframe or raster stack

### ISSUE THREAD

**Issue by albirayi** [coolbutuseless/ggpattern#52]
I have to raster stacks with 4 layers each in total 8 layers. Four of them are trends and the rest for are their statistical significance. I converted them into data frame and plot using ggplot. However, I would like to add significance layers on the respective trend layers as stipples or hatch. How can I implement this using ggpattern?

**Comment by trevorld** [comment]
Dear @albirayi,

A "minimal, reproducible" example version of this question should be posted on a community site such as Stackoverflow or RStudio Community.

Best,

Trevor

p.s. Here is a good post explaining why: https://yihui.org/en/2017/08/so-gh-email/
