### ISSUE TITLE
Deploy updated version of package website

### ISSUE THREAD

**Issue by trevorld** [coolbutuseless/ggpattern#55]
* Just realized that the documentation improvements from July never auto-made it to the companion website.
* Not quite sure how the `{pkgdown}` website gets deployed to github.io .  Maybe there is some Github Actions workflow that needs to be created?  Or @coolbutuseless needs to do something manually?

**Comment by coolbutuseless** [comment]
The ggpattern package website is created via a manual call to pkgdown.  The results are included in my github.io site.

It might be worthwhile changing this to so it's a more generally reproducible process (but this doesn't feel urgent).

For now, I've regenerated and pushed the updated docs, and it all looks good to me.
