### ISSUE TITLE
[BUG]  DLL 'colorspace' not found: maybe not installed for this architecture?

### ISSUE THREAD

**Issue by IanWorthington** [coolbutuseless/ggpattern#66]
Installing, received:

Error: package or namespace load failed for 'ggpattern' in library.dynam(lib, package, package.lib):
 DLL 'colorspace' not found: maybe not installed for this architecture?
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/IanWo/My Code Projects/R Studio Projects/Stocks exploration/renv/library/R-4.1/x86_64-w64-mingw32/ggpattern'
Warning in i.p(...) :
  installation of package ‘C:/Users/IanWo/AppData/Local/Temp/Rtmp2RXeX3/file240b4261815b3/ggpattern_0.3.2-9.tar.gz’ had non-zero exit status

Please enter here a high-level description of your bug.

**Minimal, reproducible example**

Please enter here a [minimal, reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) of your bug.  Thanks!

```r
install.packages("remotes")
remotes::install_github("coolbutuseless/ggpattern")
```

**Session info**

Please enter here the results of `xfun::session_info("ggpattern")`

```
> xfun::session_info("ggpattern")
Error in packageVersion(p) : there is no package called ‘ggpattern’
```

**Comment by trevorld** [comment]
`{colorspace}` is a dependency (of a dependency) of `{ggplot2}` which is a dependency of `{ggpattern}`.  You need to install it.

From our README:

> An installation error is highly unlikely to be an issue with {ggpattern} itself. Please don't open up a Github Issues unless you are sure it is an issue with {ggpattern} itself. If you have an error installing the package we strongly suggest that you look at all your error messages more closely to figure out which package dependency is failing to install and why. See https://thomasadventure.blog/posts/install-r-packages/ for more info on installing R packages.

**Comment by IanWorthington** [comment]
Hi Trevor.  Thanks for this.  I did check those notes, but they weren't helpful.  

I had assumed you'd like to know that there was a dependency missing.

**Comment by trevorld** [comment]
`remotes::install_github("coolbutuseless/ggpattern")` should automatically install all dependencies including dependencies of dependencies like `{colorspace}`.  Linux users may need to manually install C++ headers but CRAN will pre-compile packages for Windows.  Your example isn't a generally reproducible problem.  I don't know went wrong on your machine in this instance.
