### ISSUE TITLE
[FEAT] Use geom_bar_pattern() with additional fill variable in different position

### ISSUE THREAD

**Issue by RS-eco** [coolbutuseless/ggpattern#67]
I would like to make a bar plot, where I combine information from three variables.
So far I can use geom_bar with fill to plot two variables with position = "dodge":

``` r
library(ggplot2); library(ggpattern)

ggplot(mpg, aes(x = class)) + 
  geom_bar(aes(fill = as.factor(cyl)), position="dodge")
```

![](https://i.imgur.com/d8cW7WX.png)

Or I can use geom_bar_pattern() with position="stack":

``` r
ggplot(mpg, aes(x = class)) + 
  geom_bar_pattern(aes(pattern = drv), position="stack")
```

![](https://i.imgur.com/t5ZGG4i.png)

But how I can I combine these two into one figure, where fill is displayed with position="dodge" and pattern is displayed with position="stack"). Is this somehow possible?

**Comment by trevorld** [comment]
Couldn't you use `geom_bar()` with position "dodge" and then `geom_bar_pattern()` (with fill set to "transparent") with position "stack"?

**Comment by RS-eco** [comment]
Well, this does not really solve my problem, as the geom_bar_pattern then still does not consider the dodging by the 2nd variable:
``` r
library(ggplot2); library(ggpattern)

ggplot(mpg, aes(x = class)) + 
  geom_bar(aes(fill = as.factor(cyl)), position="dodge") + 
  geom_bar_pattern(aes(pattern = drv), fill="transparent")
```

![](https://i.imgur.com/aPWg44b.png)

**Comment by RS-eco** [comment]
Not super neat, but here the first work-around solution I came up with using `geom_rect_patter()`, just for future reference.
``` r
library(ggplot2); library(ggpattern); library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

n_cyl <- mpg %>% group_by(class) %>% 
    summarise(n_cyl = n_distinct(cyl)) %>% ungroup()
n_count <- mpg %>% group_by(class, cyl, drv) %>% 
    summarise(count=n()) %>%
    mutate(count_start = cumsum(count)-count,
           count_end = cumsum(count)) %>% ungroup()
#> `summarise()` has grouped output by 'class', 'cyl'. You can override using the `.groups` argument.
cum_cyl <- mpg %>% select(class, cyl) %>% distinct() %>%
  mutate(cyl_no = 1) %>% group_by(class) %>% 
  arrange(class, cyl) %>% summarise(cum_cyl=cumsum(cyl_no)) %>% ungroup() %>% select(-class)
#> `summarise()` has grouped output by 'class'. You can override using the `.groups` argument.
cum_cyl <- mpg %>% distinct(cyl, class) %>% arrange(class, cyl) %>% bind_cols(cum_cyl)
dat <- mpg %>% select(class, cyl, drv) %>% left_join(n_count) %>% left_join(cum_cyl) %>% 
  left_join(n_cyl) %>% distinct() %>% arrange(class, cyl, drv) %>% 
  mutate(class = as.numeric(factor(class, labels=c(1:length(unique(mpg$class)))))) %>% 
  mutate(x_start = (class-0.5)+((cum_cyl-1)/n_cyl),
         x_end = (class-0.5)+(cum_cyl/n_cyl))
#> Joining, by = c("class", "cyl", "drv")
#> Joining, by = c("class", "cyl")
#> Joining, by = "class"

ggplot(data=mpg, aes(x =class)) + 
  geom_bar(aes(fill = as.factor(cyl)), 
           position="dodge", width=1) + 
  geom_rect_pattern(data=dat,
                    aes(xmin=x_start, xmax=x_end, ymin=count_start, ymax=count_end, pattern = drv),
                    fill = 'transparent', colour  = 'black',
                    pattern_density = 0.35, pattern_spacing=0.03)
```

![](https://i.imgur.com/oXoZ6L5.png)

**Comment by trevorld** [comment]
* Technically this seems like this should be implemented as a new `{ggplot2}` "position" class:

  + https://ggplot2-book.org/extensions.html#new-positions

* Not necessarily useful just for `{ggpattern}` (i.e. people seem to want to do this with unpatterned base `geom_bar()`):

  + https://stackoverflow.com/questions/46597278/how-to-plot-a-stacked-and-grouped-bar-chart-in-ggplot/46597859#46597859
 
* Five years ago `{ggplot2}` maintainers said they had no (near-term) plans on implementing this particular "position" themselves: https://github.com/tidyverse/ggplot2/issues/2267

**Comment by trevorld** [comment]
[Also note one can achieve a similar affect via `facet_grid()`](https://stackoverflow.com/a/58029263/2121942):

```r
library(ggplot2)
library(ggpattern)

df <- transform(mpg, cyl = as.factor(cyl))

ggplot(df, aes(x = cyl)) +
    facet_grid(. ~ class) +
    geom_bar(aes(fill = cyl)) +
    geom_bar_pattern(aes(pattern = drv),
                     fill = "transparent", col = "black",
                     pattern_spacing = 0.2, pattern_density = 0.4,
                     pattern_key_scale_factor = 0.2) +
    scale_pattern_manual(values = c("none", "stripe", "circle"))
```

![ggp_facet](https://user-images.githubusercontent.com/2433259/175755571-2bfee8fd-d772-4c00-af91-25e1d1f15ec3.png)
