### ISSUE TITLE
[FEAT] Show legend in examples

### ISSUE THREAD

**Issue by bdeonovic** [coolbutuseless/ggpattern#73]
I would like to see the legend in the examples (in particular on page https://coolbutuseless.github.io/package/ggpattern/articles/geom-gallery-geometry.html)

**Comment by trevorld** [comment]
NB. five examples on that page do have a legend as well as a majority of examples in other vignettes such as https://coolbutuseless.github.io/package/ggpattern/articles/patterns-stripes.html

**Comment by bdeonovic** [comment]
Yes, I've actually found more examples on the website and gotten a pattern understanding of all of the pattern_* attributes.
