### ISSUE TITLE
Cannot have a legend without a pattern in it.

### ISSUE THREAD

**Issue by nfparsons** [coolbutuseless/ggpattern#8]
When I plot using fills and patterns I get image 1.
![Screen Shot 2020-06-03 at 11 43 46 AM](https://user-images.githubusercontent.com/26283454/83697227-53178200-a5b3-11ea-8f73-09ab2b7e4707.png)

What I'm looking for is image 2.

![Screen Shot 2020-06-03 at 3 58 30 PM](https://user-images.githubusercontent.com/26283454/83697259-60cd0780-a5b3-11ea-90c2-1d4eda885b4d.png)

Here's my code: 

dat.fac.p %>%
  filter(visn == 1) %>%
  ggplot(aes(x = station, y = value, group = visn)) + 
    geom_col_pattern(
      aes(pattern_density = plot_pattern), 
      fill = 'white',
      pattern = 'crosshatch', 
      pattern_spacing = 0.02
    ) +
    geom_col(
      aes(fill = plot_fill), 
      color = 'gray50', 
      alpha = 0.5
    ) +
    scale_pattern_density_manual(name = element_blank(), 
                                 values = c(a = 0.1, b = 0), 
                                 labels = c("Positive", "")) +
    scale_fill_viridis(name = element_blank(), 
                       discrete = TRUE,
                       labels = c("Screened", "Not Screened")) +
    theme_ipsum()

**Comment by sariya** [comment]
can you share sample data?

**Comment by M-Colley** [comment]
Maybe related: 

  ggpattern::scale_pattern_fill_manual(values=c(scale_fill_colors4[2],scale_fill_colors4[3]), breaks=c("example1", "example2"), values= c("test1", "test2"))

gives me two legends instead of one where the legends is correctly named (i.e., in this case "test1" etc)

**Comment by jkeast** [comment]
I'm having the same issue. I copied the pie graph example from the Geometry-based Patterns vignette to illustrate and added a new variable to map the fill aesthetic to. This is what I get:
![ggpattern_issue_example](https://user-images.githubusercontent.com/26280620/87673562-c11e9f80-c742-11ea-8cc2-bcc17e696acc.png)

Are there any work-arounds? Modifying pattern_key_scale_factor isn't helping.

**Comment by jkeast** [comment]
I found a work-around with override.aes! Here's the code, last line is the important one:
```
df <- data.frame(
  group = factor(c("Cool", "But", "Use", "Less"), levels = c("Cool", "But", "Use", "Less")),
  value = c(10, 20, 30, 40),
  other = factor(c("a", "b", "c", "d"),levels = c("a", "b", "c", "d"))
)

ggplot(df, aes(x="", y = value, pattern = group, pattern_angle = group))+
  geom_bar_pattern(aes(fill=other), width = 1, stat = "identity", colour = 'black', pattern_aspect_ratio = 1, pattern_density = 0.3, pattern_key_scale_factor = .5) +
  coord_polar("y", start=0) +
  theme_void(20) +
  theme(legend.key.size = unit(1, 'cm')) +
  labs(title = "ggpattern::geom_bar_pattern() + coord_polar()")+
  guides(fill = guide_legend(override.aes = list(pattern = c("none", "none", "none", "none"))))
```

and the fixed plot:
![ggpattern_issue_example2](https://user-images.githubusercontent.com/26280620/87678010-6b4cf600-c748-11ea-929e-7f361ae89597.png)

**Comment by gulinan** [comment]
Hi, 

For my data, I want to get a bar blot with specific patterns in the bar plot. I want to see the exactly same pattern in the legend keys. However, I could not get it. I would appreciate any help.

Thank you very much.

```{r}
library(ggplot2)
library(ggpattern)


df <- data.frame(level = c("a", "b", "c", 'd'), outcome = c(2.3, 1.9, 3.2, 1))
df

ggplot(df, aes(x=level, y=outcome, fill=level)) +
  geom_col_pattern(
    fill    =  c('white', 'black','white','white'),  #bar fill in color
    colour  = 'black',  #bar frame color
    pattern = c('none', 'none', 'stripe','circle'), #pattern type
    pattern_fill = c('white', 'black','black','black'), #pattern texture color
    pattern_angle = c(0,0,90,0),    #pattern placement angle
    pattern_size = c(0,0,0.1,0),    #pattern size
    ) +
    theme_bw() +
    coord_fixed(ratio = 1/2)
```

![Rplot](https://user-images.githubusercontent.com/56047198/129576320-fbb6e7a1-1686-4459-b526-6d4538be7dd8.jpeg)

**Comment by trevorld** [comment]
@nfparsons, @jkeast seems to provide a solution for legends with "two separate groups" separately controlling color and patterns case.  An alternative solution would be to create 3 groups: "Positive" (and screened), "Screened" (and not positive), "Not Screened" and then use the crosshatch pattern for the "Positive" group and the "none" pattern for the other two groups and then color the "Not Screened" group yellow and the other two groups purple.
