### ISSUE TITLE
Bug when height is 0 in `geom_col_pattern` and `pattern = "gradient"`

### ISSUE THREAD

**Issue by tomicapretto** [coolbutuseless/ggpattern#9]
Hi, 

I have been using `geom_col_pattern()` to create some barplots with gradient fill and I want to thank you for the great package. 
I found what I think is a bug and I would like to report it. The following is not exactly my case, but it is enough to report what I found.

When the heights are positive, the code works correctly.

```
suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(ggpattern)
})
set.seed(1234)
ORANGE <- "#ff8a3f"
PINK <- "#fe0060"

data <- data.frame(
  x = c(1, 2 ,3),
  count = sample.int(20, 3)
)

ggplot() +
  geom_col_pattern(
    data = data,
    aes(
      x = x,
      y = count
    ),
    pattern_fill = PINK,
    pattern_fill2 = ORANGE,
    pattern = "gradient",
    colour = "#FFFFFF" 
  ) +
  labs(
    title = "All heights positive, works well."
  )
```

![plot_1](https://user-images.githubusercontent.com/25507629/84508571-dd897100-ac98-11ea-9001-a7dff72a3205.png)

However, if the height is 0 in any case, it fails
```
data_0 <- data.frame(
  x = c(1, 2 ,3),
  count = c(sample.int(20, 2), 0)
)

ggplot() +
  geom_col_pattern(
    data = data_0,
    aes(
      x = x,
      y = count
    ),
    pattern_fill = PINK,
    pattern_fill2 = ORANGE,
    pattern = "gradient",
    colour = "#FFFFFF" 
  )
```
With the following error

```
Error in png(png_file, width = width, height = height) : 
  invalid 'width' or 'height'
In addition: Warning message:
In FALSE :
  create_pattern_array(): Expecting a numeric RGBA array with dim = c(0, 246, 4) but instead got a "array" of type double with dimensions c(1L, 246L, 4L)
```

If instead of 0 you have `NA` it works, but the value of `x` is not dislpayed in the plot (as expected, since `geom_col()` does the same)

```
data_na <- data.frame(
  x = c(1, 2 ,3),
  count = c(sample.int(20, 2), NA)
)

ggplot() +
  geom_col_pattern(
    data = data_na,
    aes(
      x = x,
      y = count
    ),
    pattern_fill = PINK,
    pattern_fill2 = ORANGE,
    pattern = "gradient",
    colour = "#FFFFFF" 
  ) +
  labs(
    title = "NA makes it work again"
  )
```

![plot2](https://user-images.githubusercontent.com/25507629/84508849-4e308d80-ac99-11ea-95e8-2f20279fd4e6.png)

However, `geom_col()` works well with both heights of 0 and `NA`. In the first case, it includes
the horizontal value, with a height of 0, and in the latter, it is dropped.

```
ggplot(data_0) +
  geom_col(aes(x = x, y = count), fill = ORANGE)

ggplot(data_na) +
  geom_col(aes(x = x, y = count), fill = ORANGE)
```
![plot_3](https://user-images.githubusercontent.com/25507629/84509028-9059cf00-ac99-11ea-84bd-35168034476f.png)
![plot_4](https://user-images.githubusercontent.com/25507629/84509029-90f26580-ac99-11ea-8279-771643d1665c.png)

Thank you again! 
Tomas

**Comment by ndayasse** [comment]
I am sometimes running into this error when trying to combine geom_col_pattern using pattern='image' with patchwork to combine plots. I have not yet been able to figure out what makes it occur vs not; I did try having the image not appear in very small bars (values below 1 on my plot) or 0 bars but that did not fix it. The issue does not occur when using cowplot to combine plots instead, however unfortunately I am not able to produce the layout I am looking for using cowplot.

**Comment by trevorld** [comment]
* Please share a [minimum, reproducible example](https://stackoverflow.com/a/5963610/2121942). 
* Since this seems to be a "new" issue please open up a new issue for it.
* Thanks!
