### ISSUE TITLE
[BUG] 'geom_col_pattern()' with numeric x values

### ISSUE THREAD

**Issue by xlea23** [coolbutuseless/ggpattern#93]
**Bug description**

Using ggpattern package in R, how can I not show a pattern for "NA" values but then have patterns continue after that point? When I run this code, there are no more patterns after an "NA" value even though there should be. There is a problem with ggpattern when it comes to repeating patterns.In the below code, you can see that fill acts appropriately, but pattern will never repeat twice, which causes the pattern from "S" to split over into the second red bar, which shouldn't have any pattern because it's "NA". See more information [here](https://stackoverflow.com/questions/75252694/ggpattern-missing-pattern-after-na-values/75269886#75269886).

**Minimal, reproducible example**

```r
library(ggpattern)
library(tidyverse)

df <- data.frame(
  study_id = c(3, 3, 3, 3), primary_therapy = c("Si", "Si", "Si", "Si"),
  additional_therapy = c("NA", "S", "NA", "V+S"), end_yr = c(0.08, 0.39, 3.03, 3.4)) 

df %>%
  ggplot(aes(x = end_yr, y = study_id)) + 
  geom_col_pattern(aes(pattern = additional_therapy, 
                       fill = additional_therapy),
                   color = NA,
                   show.legend = TRUE,
                   position = "fill",
                   width = 3,
                   pattern_spacing = 0.01,
                   pattern_fill = "black",
                   pattern_color = NA,
                   pattern_size = 0.5,
                   pattern_density = 0.1,
                   pattern_linetype = 0.5,
                   pattern_orientation = "vertical") +
  scale_pattern_manual(
    name = "Additional Therapy",
    breaks = c("S", "V", "V+S"),
    values = c("S" = "stripe", "V" = "circle", "V+S" = "crosshatch", "NA" = "none"))
```

<img width="722" alt="image" src="https://user-images.githubusercontent.com/123842870/215294368-2e673484-4240-4091-a653-7e4882961931.png">

**Session info**

Please enter here the results of `xfun::session_info("ggpattern")`

**Comment by trevorld** [comment]
* Thanks for the bug report
* This seems to be a bug with `geom_col_pattern()` with numeric x values (instead of say factor values).  For some reason it looks like in this case we are drawing the patterns in a different (wider) region than the color fills.  This doesn't seem to be connected to the pattern repeating and is observed when we don't have repeated patterns.
* A more minimal reproducible example:

```r
library(ggplot2)
library(ggpattern)

df <- data.frame(trt = c("a", "b"),
                 x = c(0.08, 0.39),
                 y = rep(1, 2))

df %>%
  ggplot(aes(x = x, y = y)) +
  geom_col_pattern(aes(pattern = trt, fill = trt),
                   color = NA,
                   show.legend = TRUE,
                   position = "fill",
                   width = 3) +
  scale_pattern_manual(
    values = c("a" = "stripe", "b" = "circle", "c" = "none"))
```

![ggp_bug](https://user-images.githubusercontent.com/2433259/215540903-9422a44c-8509-4396-987b-a31d67781dbd.png)

**Comment by trevorld** [comment]
Nota bene: @xlea23 if you just need to draw rectangles with numeric x and y axes then `geom_rect_pattern()` seems to currently be working correctly and (with a bit of work) should be able to produce the targeted chart...

**Comment by trevorld** [comment]
* Upon further examination this does not appear to be a bug.
* @xlea23, in your example you're columns are overlapping
* Within a single `geom_*_pattern()` call `{ggpattern}` first draws the polygon fill colors, then the patterns, and then the polygon borders.  In your case the green "S" column (with stripes) overlaps with the right pink "NA" column (with no pattern).  The pink fill covers up the green fill and then nothing covers up the stripe and then you instructed fully transparent polygon borders...
* Here is `ggplot2::geom_col()` with `alpha = 0.5` to show this overlap occurs in base `{ggplot2}`...

```r
library(ggplot2)

df <- data.frame(
  study_id = c(3, 3, 3, 3), primary_therapy = c("Si", "Si", "Si", "Si"),
  additional_therapy = c("NA", "S", "NA", "V+S"), end_yr = c(0.08, 0.39, 3.03, 3.4))

df %>%
  ggplot(aes(x = end_yr, y = study_id)) +
  geom_col(aes(fill = additional_therapy),
           color = NA,
           show.legend = TRUE,
           position = "fill",
           width = 3,
           alpha = 0.5)
```

![ggp_bug](https://user-images.githubusercontent.com/2433259/215657043-63ba50a9-6f36-4f46-a277-5a0f8d755f18.png)
